security:
    providers:
        session_provider:
            memory: ~
        blog_user_provider:
            id: temirkhan.user.provider.user
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        blog:
            anonymous: ~
            provider: blog_user_provider
            pattern: ^/
            logout:
                path: /logout
                target: /
            logout_on_user_change: true
    encoders:
        Temirkhan\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

