version: '2'
services:
  frontend:
    image: nginx:alpine
    volumes_from:
      - backend
    ports:
      - "80:80"
    links:
      - backend
    depends_on:
      - backend
    command: sh -c "envsubst '' < /var/www/html/docker/blog-nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  backend:
    build: ./
    volumes:
      - ./:/var/www/html
    links:
      - db
    depends_on:
      - db
    command: sh -c "chmod +x ./docker/init.sh && ./docker/init.sh"
  db:
    image: sameersbn/postgresql
    environment:
      - DB_USER=blog_user
      - DB_PASS=blog_pass
      - DB_NAME=blog_db
    ports:
      - 5432
