#Страница решистрации
blog_register:
    path: /registration
    defaults: { _controller: blog.controller.author.register:execute }

# Страница входа
blog_login:
    path: /login
    defaults: { _controller: blog.controller.auth.login:execute }

#Основая страница блога со списком публикаций
blog_posts:
    path: /{page}
    defaults: { _controller: blog.controller.post.list:execute, page: 1 }
    requirements:
        page: '[1-9][0-9]*'

#Страница с публикациями автора
author_posts:
    path: /authors/{author}/{page}
    defaults: { _controller: blog.controller.author.post_list:execute, page: 1}
    requirements:
        page:   '[1-9][0-9]*'
        author: '[1-9][0-9]*'

#Страница с публикацией
blog_post:
    path: /posts/{post}
    defaults: { _controller: blog.controller.post.view:execute }
    requirements:
        post: '[1-9][0-9]*'

#Страница добавления публикации
add_post:
    path: /posts/add
    defaults: { _controller: blog.controller.post.create:execute }
    methods: [POST, GET]

#Страница редактирования публикации
edit_post:
    path: /posts/{postId}/edit
    defaults: { _controller: blog_bundle.controller.post:updateContentAction }
    requirements:
        postId: '[1-9][0-9]*'

#Страница выноса публикаций из черновиков в опубликованные
publish_post:
    path: /posts/{postId}/publish
    defaults: { _controller: blog_bundle.controller.post:publishContentAction }
    requirements:
        postId: '[1-9][0-9]*'

#Страница удаления публикации
delete_post:
    path: /posts/{postId}/delete
    defaults: { _controller: blog_bundle.controller.post:deleteContentAction }
    requirements:
        postId: '[1-9][0-9]*'

#Страница добавления комментария к публикации
add_comment:
    path: /posts/{postId}/comment/add
    defaults: { _controller: BlogBundle:Comment:createComment }
    requirements:
        postId: '[1-9][0-9]*'
